site_name: 日本版リタイア後の取り崩し戦略 〜 4%ルールを信じるな | たきびFIRE
site_dir: dist
use_directory_urls: false

theme:
  language: ja
  name: material
  favicon: imgs/favicon.png
  logo: imgs/takibi.png
  font:
    text: Noto Sans JP
    code: Roboto Mono
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: ダークモードに切り替え
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: ライトモードに切り替え
  features:
    - content.code.copy
    - content.tooltips
    - navigation.expand
    - navigation.instant
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow

copyright: Copyright &copy; 2026 たきびFIRE

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TakibiFire/JapaneseTrinityStudy
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/takibi333
      name: たきび@FIRE

extra_css:
  - stylesheets/tailwind.css
  - stylesheets/extra.css

plugins:
  - search:
      lang: ja
      separator: '[\s\-\.]+'
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Tokyo
      locale: ja
      fallback_to_build_date: true

markdown_extensions:
  - admonition
  - attr_list
  - markdown_include.include:
      base_path: docs
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
      smart_dollar: false
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.striphtml:
      strip_comments: true
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - リタイア後の取り崩し戦略: index.md
  - 取り崩し戦略に必要な知識:
    - ボラティリティが長期投資に与える影響: volatility.md
    - 資産が枯渇するパターン：収益率配列のリスク: sequence.md
    - 物価上昇率の影響: cpi.md
    - 譲渡所得税の影響: tax.md
    - 信託報酬の影響: trust_fee.md
    - 為替リスクの影響: forex.md
    - 購買力平価とインフレの相関: ppp.md
    - ファットテール分布の影響: fat_tails.md
    - S&P500 vs. オルカン: sp500_vs_acwi.md
  - 生存確率を上げる戦略:
    - 現金保有の効果: cash_ratio.md
    - 現金リバランスの効果: cash_rebalance.md
    - 無リスク資産保有の効果: zero_risk.md
    - 無リスク資産リバランスの効果: zero_risk_rebalance.md
    - ダイナミックリバランス戦略: dynamic_rebalance.md
    - ダイナミック・スペンディング戦略: dynamic_spending.md
    - 高齢になると支出が減る: retired_spending.md
    - 年金支払いと受給の効果: pension.md
    - サイドFIREの効果: side_fire.md
    - 死亡率を考慮する: mortality.md
    - 公開予定 / NISA: nisa.md
    - 公開予定 / iDeco: ideco.md
  - 何%ルールなのか:
    - 最適戦略を試してみる: all_combinations.md
